name: Deploy to DirectAdmin

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Deploy to DirectAdmin
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DA_HOST }}
          username: ${{ secrets.DA_USERNAME }}
          key: ${{ secrets.DA_SSH_KEY }}
          source: "out/*"
          target: "/home/${{ secrets.DA_USERNAME }}/domains/exploresylva.com/public_html/"
          strip_components: 1 