name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm ci
          npm install -g prisma
          
      - name: Build
        run: npm run build
        env:
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        
      - name: Create deployment package
        run: |
          mkdir -p deploy
          cp -r .next deploy/
          cp -r public deploy/
          cp -r package.json deploy/
          cp -r package-lock.json deploy/
          cp -r next.config.js deploy/
          cp -r .env deploy/
          cp -r prisma deploy/
          cp -r server.js deploy/
          
      - name: Deploy to DirectAdmin
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DA_HOST }}
          username: ${{ secrets.DA_USERNAME }}
          key: ${{ secrets.DA_SSH_KEY }}
          source: "deploy/*"
          target: "/home/${{ secrets.DA_USERNAME }}/domains/exploresylva.com/public_html/"
          strip_components: 0
          overwrite: true
          
      - name: Run deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DA_HOST }}
          username: ${{ secrets.DA_USERNAME }}
          key: ${{ secrets.DA_SSH_KEY }}
          script: |
            cd /home/${{ secrets.DA_USERNAME }}/domains/exploresylva.com/public_html/
            npm install
            npx prisma generate
            npx prisma db push
            pm2 restart all || pm2 start server.js --name "exploresylva" 