name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          npm install -g prisma
          
      - name: Generate Prisma Client
        run: npx prisma generate
        
      - name: Run type check
        run: npm run type-check
        
      - name: Build
        run: npm run build
        env:
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL || 'http://localhost:3000' }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET || 'development-secret' }}
          DATABASE_URL: ${{ secrets.DATABASE_URL || 'postgresql://user:password@localhost:5432/mydb' }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME || 'admin' }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD || 'password' }}
          
      - name: Run linting
        run: npm run lint
      
      # Add more steps here when you decide on a new hosting provider 